spring:

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:activiti}?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&verifyServerCertificate=false&createDatabaseIfNotExist=true&serverTimezone=GMT%2B8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:admin}
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql-script-encoding: utf-8

  jpa:
    show-sql: ${SHOW_SQL:true}
    database-platform: cc.powind.activiti.impl.MySQL57InnoDBDialectUtf8mb4
    hibernate:
      ddl-auto: update

  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true
    useStrongUuids: false
#    check-process-definitions: false